### ISSUE TITLE
Refresh workspace after poetry-add or poetry-remove on lsp-mode

### ISSUE THREAD

**Issue by ig-perez** [cybniv/poetry.el#28]
Hi, thanks for maintaining this package!

I'm an `lsp-mode` user and the snippet provided by [@jidicula](https://github.com/galaunay/poetry.el/issues/25#issuecomment-680266270) works great to determine the correct virtual env. 

But when a dependency is added or removed you have to manually execute `lsp-workspace-restart` so the library changes are available to the project.

Is it possible to execute this command after every `poetry-add` or `poetry-remove` if LSP-mode is used?

Thanks!

**Comment by calebstewart** [comment]
Internally, `poetryl.el` uses `pyvenv` to manage the current virtual environment (see [here](https://github.com/cybniv/poetry.el/blob/master/poetry.el#L468-L474)). I solved this by adding the following to my Emacs configuration:

```elisp
; Run lsp-restart-workspace whenever the pyvenv changes
(add-hook 'pyvenv-post-activate-hooks (lambda () (lsp-restart-workspace)))
(add-hook 'pyvenv-post-deactivate-hooks (lambda () (lsp-restart-workspace)))
```

On the upside, if you use `pyvenv` for projects that don't use Poetry, then this should also work there as well.

**Comment by ig-perez** [comment]
Awesome, thanks @calebstewart , I'll give it a try.
