### ISSUE TITLE
README: not maintained at the moment

### ISSUE THREAD

**Issue by galaunay** [cybniv/poetry.el#31]
I am not able to maintain poetry.el at the moment.

I hope I will soon be able to take care of this again, but in the meantime, I am afraid any issue report or PR will be left unanswered.
If you happen to be willing to make a fork and maintain poetry.el, please email me directly, I will gladly redirect Melpa and users to your fork !

**Comment by cybniv** [comment]
I gladly took over and use this package on a daily basis. Started to look into open issues and PRs 👍
