### ISSUE TITLE
Package broken on OSX

### ISSUE THREAD

**Issue by jellyfish-tech** [cybniv/poetry.el#49]
Every interaction with poetry fails with next message

`[projectname] Could not find poetry executable`

In my opinion, issue originates from this commit.

https://github.com/cybniv/poetry.el/commit/5340ec3e83b053b8b67ec8229dd298689d961795

The main problem is that there is no section for `darwin` type system which leads to raising an error, while executable is perfectly findable.

I fixed that locally, so I can try to create PR with this fix

**Comment by Sukonnik-Illia** [comment]
I have the same issue on my Mac (
I'm not into Elisp too much, but I will try to add a line for Darwin (fixed it locally and it helped)

**Comment by cybniv** [comment]
Hotfixed with https://github.com/cybniv/poetry.el/pull/50, 🙏 @Sukonnik-Illia

**Comment by Sukonnik-Illia** [comment]
My first commit in open source ))
